# Site settings
title: Robert Liu's Home Page
description: >
  Robert Liu's public site and thoughts.
baseurl: /
url: cordyceptive.github.io

# Sidebar contents
sidebar:
  - text: Home
    url: /
  - text: About
    url: /about.html
  - text: Notes
    url: /notes.html
  - text: Projects
    url: /projects.html

# Projects
projects:
  - name: Bepsi
    description: it's good to drink
    link: https://www.pepsi.com/en-us/
    image: https://pics.me.me/pepsi-bepis-dankmemes-good-old-bepsi-10896779.png
