# Site settings
title: Robert Liu's Home Page
description: >
  Robert Liu's public site and thoughts.
baseurl: /
url: cordyceptive.github.io

# Sidebar contents
sidebar:
  - text: Home
    url: /
  - text: About
    url: /about.html
  - text: Notes
    url: /notes.html
  - text: Projects
    url: /projects.html

# Projects
projects:
  - name: Fall '18 Independent Work
    description: Multivariate Network Visualizations for Mountaineering History
    link: http://publications.americanalpineclub.org/
    image: https://i.gyazo.com/f503d630fa062caafbcec9fa55dcc179.png
  - name: CLI Hangman
    description: Quick Hangman game for your terminal
    link: https://github.com/cordyceptive/cli-hangman
    image: https://i.gyazo.com/1b6945593fbf4226df2041a84b16d232.png
